In [27]:
import torch

# for activation functions 
from torch.nn import functional as F

In [2]:
# torch.multinomial

# define a probability tensor
probabilities = torch.tensor([0.1, 0.1, 0.8])
# each probability points to the index for the probability in the tensor

# draw 10 samples from the multinomial distribution
# 'num_samples', 'replacement' as labels are optional
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)


tensor([2, 2, 2, 2, 2, 2, 2, 1, 2, 2])


In [3]:
# torch.cat; concatenate tensors

tensor = torch.tensor([1,2,3,4])
tensor2 = torch.tensor([5,6,7])
out = torch.cat((tensor, tensor2, torch.tensor([8])), dim=0)
out

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
# lower triangle

out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [25]:
# upper triangle

out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [34]:
# masked fill

out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out


tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [35]:
# then, take masked fill and use torch.exp to exponentiate the above tensor
# e^-inf = 0
# e^0 = 1
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [37]:
# transposing
# transpose 1st and 3rd dimensions of a tensor

input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [38]:
# stacking

tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor



tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [46]:
import torch.nn as nn
sample = torch.tensor([10., 10. ,10.])
linear = nn.Linear(in_features=3, out_features=3, bias=False)
print(linear(sample))

tensor([-2.6164, -7.1098, -2.5346], grad_fn=<SqueezeBackward4>)


In [45]:
linear

Linear(in_features=3, out_features=3, bias=False)

In [53]:
# coded softmax example

import torch.nn.functional as F

# create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

softmax_output

tensor([0.0900, 0.2447, 0.6652])

In [69]:
# using nn.embeddings to convert characters into
# continuous vector representations

import torch.nn as nn
import torch

# Define the embedding layer
vocab_size = 26  # Number of unique characters (lowercase letters)
embedding_dim = 5  # Dimensionality of the character embeddings
embedding_layer = nn.Embedding(vocab_size, embedding_dim)

# Create input tensor for each letter (using character integer IDs)
# 'a' maps to 0, 'b' to 1, 'c' to 2, ..., 'z' to 25
input_characters = torch.arange(0, vocab_size)

# Pass the input tensor through the embedding layer
embedded_characters = embedding_layer(input_characters)

# Display the embedding vectors for each letter to 4 decimal places
for char_id, embedding_vector in zip(input_characters, embedded_characters):
    char = chr(ord('a') + char_id)  # Convert integer ID back to character
    embedding_str = ', '.join(f'{val:.4f}' for val in embedding_vector.tolist())
    print(f'Character: {char}, Embedding Vector: [{embedding_str}]')



Character: a, Embedding Vector: [0.1940, -1.7591, 0.6698, 0.7262, -0.2697]
Character: b, Embedding Vector: [-0.5946, -1.3047, -1.3019, -0.6299, 0.1252]
Character: c, Embedding Vector: [-0.3974, -1.3289, 1.5256, -0.6225, -1.6559]
Character: d, Embedding Vector: [-1.0803, -1.1033, -1.3195, -1.7267, -0.2344]
Character: e, Embedding Vector: [-1.0192, 1.3235, -1.4954, 0.9990, 0.1959]
Character: f, Embedding Vector: [-0.7917, 0.5518, 0.9541, -0.2166, -1.4188]
Character: g, Embedding Vector: [0.0597, 1.4350, 0.6724, -0.3784, -0.7632]
Character: h, Embedding Vector: [1.3754, -0.0591, 0.5397, 1.7889, -0.5520]
Character: i, Embedding Vector: [1.4194, 1.8319, -0.1274, 1.8793, -1.9487]
Character: j, Embedding Vector: [-0.2142, 0.8919, 0.0124, 0.4151, -0.5576]
Character: k, Embedding Vector: [0.3900, 1.1649, 1.2757, -0.7011, -2.4038]
Character: l, Embedding Vector: [-0.4315, 0.7219, 1.4770, 0.0626, 0.4772]
Character: m, Embedding Vector: [1.4890, -0.0096, -0.7390, 0.7835, 1.5618]
Character: n, Embe

In [80]:
# simple 4x2, 2x3 matrix multiplication

a = torch.tensor([[1,2], [3,4], [5,6], [13,14]])
b = torch.tensor([[7,8,9], [10,11,12]])

print(a.shape)
print(b.shape)
print(a @ b)
print(torch.matmul(a, b))

torch.Size([4, 2])
torch.Size([2, 3])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117],
        [231, 258, 285]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117],
        [231, 258, 285]])


In [6]:
int_64 = torch.randint(1, (3, 2)).float()
float_32 = torch.rand(2,3)
print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

torch.float32 torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [29]:
# activation functions:
# can use torch.nn.functional or torch

x = torch.tensor([-0.05, 0.4], dtype=torch.float32)
y = F.relu(x) 
z = torch.sigmoid(x)
z2 = F.tanh(x)

print(y, z, z2)


tensor([0.0000, 0.4000]) tensor([0.4875, 0.5987]) tensor([-0.0500,  0.3799])
